update-documentation
FifthTry/header pull request #44
Opened 2023-05-08 11:10 UTC by priyanka9634

update-documentation

2023-05-08 12:20 UTC, gsalunke requested changes

2023-05-08 12:20 UTC, gsalunke commented on index.ftd
> +This is a default optional property of the
```suggestion

```

2023-05-08 13:31 UTC, gsalunke requested changes

2023-05-08 13:31 UTC, gsalunke commented on index.ftd
> +`header` component.
```suggestion
Its used to pass `products` record list to `header` component. `products` property will be passed to `product-switcher` which is imported by default inside `header` component `FASTN.ftd`.
```

2023-05-08 13:31 UTC, gsalunke commented on index.ftd
> +Using `sitemap processor` or
```suggestion
It's used to show `fastn.sitemap` sections.
```

2023-05-08 13:31 UTC, gsalunke commented on index.ftd
> +`header` component.
```suggestion
```

2023-05-08 13:31 UTC, gsalunke commented on index.ftd
> +to `header` component.
```suggestion
It's used to show `fastn.sitemap` sub-sections.
```

2023-05-08 13:31 UTC, gsalunke commented on index.ftd
> +`header` component.
```suggestion
It's used to show `fastn.sitemap` toc.
```

2023-05-08 13:31 UTC, gsalunke commented on index.ftd
> +added current-section to `header` component.
```suggestion
It's used to show `fastn.sitemap` current active section.
```

2023-05-08 13:31 UTC, gsalunke commented on index.ftd
> +added current-subsection to `header` component.
```suggestion
It's used to show `fastn.sitemap` current active sub-section.
```

2023-05-08 13:31 UTC, gsalunke commented on index.ftd
> +added current-page to `header` component.
```suggestion
It's used to show `fastn.sitemap` current active page.
```

2023-05-08 13:31 UTC, gsalunke commented on index.ftd
> +It’s used to add a login button to `header` component.
```suggestion
It’s used to enable login button into `header` component. Login button appears at the right side of header component.
```

2023-05-08 13:31 UTC, gsalunke commented on index.ftd
> +It’s used to add a pricing button to `header` component.
```suggestion
```

2023-05-08 13:31 UTC, gsalunke commented on index.ftd
> +-- site-doc.component-property: `pricing-cta`
@priyanka9634 remove this property from `header`

2023-05-08 13:31 UTC, gsalunke commented on index.ftd
> +It’s used to add a height to logo to `header` component.
```suggestion
It’s used to add a height to logo to `header` component. Its CSS unit is `px`
```

2023-05-09 12:51 UTC, gsalunke approved these changes

2023-05-09 12:51 UTC, gsalunke commented on index.ftd
> +logo-height: 38
```suggestion
logo-height: 38
logo-width: 120
```

2023-05-09 12:51 UTC, gsalunke commented on index.ftd
> +github-link: https://fifthtry.github.io/header
```suggestion
github-link: https://github.com/FifthTry/header
```

2023-05-09 12:51 UTC, gsalunke commented on index.ftd
> +`header` component. Its CSS unit is `px`
```suggestion
-- site-doc.component-property: `logo-height`

It’s used to add a height to logo to 
`header` component. Its CSS unit is `px`

-- site-doc.component-property: `logo-width`

It’s used to add a width to logo to 
`header` component. Its CSS unit is `px` and default value is `120`

```

2023-05-09 12:51 UTC, gsalunke commented on index.ftd
> +default: Default
```suggestion
-- site-doc.table-of-property: `logo-height`
type: Integer
default: Optional

-- site-doc.table-of-property: `logo-width`
type: Integer
default: Optional
```

2023-05-10 12:01 UTC, Heulitig commented on docs/header-with-login.ftd
> +-- import: fastn-community.github.io/site-doc
Remove this import. This is already done once

```suggestion
```

2023-05-10 12:34 UTC, Heulitig commented on docs/header-with-login.ftd
> +The `Header` package(fifthtry.github.io/header). Use inside `FASTN` files
```suggestion
The `header` package(fifthtry.github.io/header). Use inside `FASTN` files
```

2023-05-10 12:38 UTC, Heulitig commented on docs/header-with-login.ftd
> +It’s used to add a link to click
```suggestion
It’s used to add a link
```

2023-05-10 12:50 UTC, Heulitig commented on docs/header-with-login.ftd
> +It’s used to add login button text in `header` component.
```suggestion
It’s used to specify login button text in `header` component.
```

2023-05-10 12:50 UTC, Heulitig commented on docs/header-with-login.ftd
> +It’s used to add login button url in `header` component.
```suggestion
It’s used to specify login button url in `header` component.
```

2023-05-10 12:52 UTC, Heulitig commented on docs/header-with-login.ftd
> +Below table shows all properties at a glance
```suggestion
Below table shows all properties
```

2023-05-10 12:53 UTC, Heulitig commented on docs/header-with-logo-site-name.ftd
> +-- import: fastn-community.github.io/site-doc
Remove this import

```suggestion
```

2023-05-10 12:56 UTC, Heulitig reviewed
Similar content is repeated in several files, so similar corrections are required in all of them

2023-05-11 04:46 UTC, merged